version: '3.1'

services:
  ds-db-service:
    image: 'postgres:latest'
    container_name: ds-db
    ports:
      - "5432:5432"
    volumes:
      - ../data/db-data/:/var/lib/postgresql/data/
      - ../scripts/db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: $DS_POSTGRES_USER
      POSTGRES_PASSWORD: $DS_POSTGRES_PASSWORD
      POSTGRES_DB: $DS_POSTGRES_DB

  ds-pgadmin-service:
    container_name: ds-pgadmin4
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $DS_PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $DS_PGADMIN_DEFAULT_PASSWORD
    volumes:
      - ../data/pgadmin-data/:/var/lib/pgadmin
