version: '3.1'

services:
  ds-db-service:
    container_name: ds-db
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    volumes:
      - ../data/db-data/:/var/lib/postgresql/data/
      - ../scripts/db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: $DS_POSTGRES_USER
      POSTGRES_PASSWORD: $DS_POSTGRES_PASSWORD
      POSTGRES_DB: $DS_POSTGRES_DB

  ds-pgadmin-service:
    container_name: ds-pgadmin4
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $DS_PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $DS_PGADMIN_DEFAULT_PASSWORD
    volumes:
      - ../data/pgadmin-data/:/var/lib/pgadmin

  ds-grafana:
    container_name: ds-grafana
    image: grafana/grafana:8.2.6
    ports:
      - 3000:3000
    volumes:
      - ../data/grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: $DS_GRAFANA_PASSWORD

volumes:
  grafana-data:
